# Generated by Django 5.0.1 on 2024-01-24 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_employee_primes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prime',
            name='date_creation',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
